runtime: python310
env: standard
service: default
entrypoint: gunicorn -b :$PORT main:APP

automatic_scaling:
  min_idle_instances: '1'
  max_idle_instances: '1'
  min_pending_latency: automatic
  max_pending_latency: automatic

includes:
  - secret.yaml